name: backup

on:
  workflow_call:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ORG_AWS_BACKUP_ROLE_ARN }}
        aws-region: eu-north-1

    - name: Sync repository to S3
      env:
        BUCKET_NAME: ${{ secrets.ORG_AWS_BACKUP_BUCKET_NAME }}
        REPO_NAME: ${{ github.repository }}
      run: |
        aws s3 sync . s3://$BUCKET_NAME/$REPO_NAME --delete

